### ISSUE TITLE
Reference Episerver.CMS.Core 12.4.2 instead of 12.5.0

### ISSUE THREAD

**Issue by ErikHen** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#12]
Hi Vincent, sorry for bugging you again 😉.
In your nuspec you have set that Episerver.CMS.Core 12.5.0 is required (but the .csproj only references 12.4.2), this makes it a bit messy to install Baaijte.Optimizely.ImageSharp.Web 2.0.0. Because not even Episerver.CMS 12.6.0 uses Episerver.CMS.Core 12.5.0 (which is a bit odd). So you need to reference Episerver.Framework 12.5.0 + Episerver.CMS.Core 12.5.0 directly in the project. This will give you compiler warnings, and the dependency tree is "broken", and it will be a slight headache in future upgrades.

I really understand the lack of time, but this would be a quite quick change.
Let me know if there is anything I can do to help.

**Comment by ddprince-yaksa** [comment]
Hey @ErikHen ! 

In fact, I fixed it and even provided a Pull Request: https://github.com/vnbaaij/Baaijte.Optimizely.ImageSharp.Web/pull/11

You can freely build our fork if you'd like, we're using our modified version because of similar issues.

**Comment by ErikHen** [comment]
With the newer version of CMS this is no longer relevant.
