### ISSUE TITLE
404 BlobNotFound on DXP

### ISSUE THREAD

**Issue by Cheryl-Kellas** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#13]
I have deployed this package along with the [SixLabors.ImageSharp.Web.Providers.Azure](https://github.com/SixLabors/ImageSharp.Web) and [PictureRenderer.Optimizely](https://github.com/ErikHen/PictureRenderer.Optimizely) packages to an Optimizely DXP environment.

Resized images on DXP (i.e. with querystring parameters) are returning a 404 error:

/globalassets/images/biography/bio-pic.png?width=296&height=274&quality=80

The same image without parameters works fine:

/globalassets/images/biography/bio-pic.png

I have the following in Startup.cs:

```
services.AddImageSharp()
                .Configure<AzureBlobStorageCacheOptions>(o =>
                {
                    o.ConnectionString = blobConnectionString;
                    o.ContainerName = "mysitemedia";
                })
                .ClearProviders()
                .AddProvider<BlobImageProvider>()
                .SetCache<AzureBlobStorageCache>();
```

I also added the AzureBlobStorageImageProviderOptions as below, but it did not fix the issue:

```
services.AddImageSharp()
                .Configure<AzureBlobStorageImageProviderOptions>(o =>
                {
                    o.BlobContainers.Add(new AzureBlobContainerClientOptions()
                    {
                        ConnectionString = blobConnectionString,
                        ContainerName = "mysitemedia"
                    });
                })
                .ClearProviders()
                .AddProvider<AzureBlobStorageImageProvider>()
                .Configure<AzureBlobStorageCacheOptions>(o =>
                {
                    o.ConnectionString = blobConnectionString;
                    o.ContainerName = "mysitemedia";
                })
                .ClearProviders()
                .AddProvider<BlobImageProvider>()
                .SetCache<AzureBlobStorageCache>();
```
Am I missing any configuration still for DXP sites?

**Comment by vnbaaij** [comment]
It should work with the DXP steps as described in the Readme. These steps were specifically added after someone else setup DXP successfully. I don't have a DXP environment myself to test with. Maybe you can ask on World discussion forums?
