### ISSUE TITLE
Cannot install into a CMS 12 site running version 12.11.0

### ISSUE THREAD

**Issue by GeekInTheNorth** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#15]
I have a CMS 12 solution which is running at the latest version of CMS -> 12.11.0

When I try and install the Baaijte.Optimizely.ImageSharp.Web, I get a conflict error.

```
NU1107: Version conflict detected for EPiServer.Framework. Install/reference EPiServer.Framework 12.9.0 directly to project Cms.Web to resolve this issue. 
 Cms.Web -> Baaijte.Optimizely.ImageSharp.Web 2.1.0 -> EPiServer.CMS.Core 12.9.0 -> EPiServer.Framework (= 12.9.0) 
 Cms.Web -> EPiServer.CMS 12.11.0 -> EPiServer.Hosting 12.8.0 -> EPiServer.Framework (= 12.8.0).
```

**Comment by GeekInTheNorth** [comment]
My uses the standard EPiServer.CMS 12.11.0 and no other EPiServer packages have been manually added.  I did resolve this by manually installing EPiServer.Framework and EPiServer.Framework.AspNetCore at their latest versions.  This is because EPiServer.CMS 12.11.0 pulls in the lowest compatible version of EPiServer.Framework at 12.8.0 with is then a conflict for this package.

I can also install at Baaijte.Optimizely.ImageSharp.Web v2.0.0 and not have the issue.

I opted for the later as it does not require me to install any EPiServer package beyond EPiServer.CMS

**Comment by GeekInTheNorth** [comment]
If you update the CSPROJ for the package and replace the installed packages with the following:

```
  <ItemGroup>
    <Compile Remove="modules\**" />
    <EmbeddedResource Remove="modules\**" />
    <None Remove="modules\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="$(UserProfile)\.nuget\packages\**\*.zip" />
    <None Remove="$(UserProfile)\.nuget\packages\**\*.config" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="EPiServer.CMS" Version="12.11.0" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="2.1.3" />
	  <PackageReference Include="SixLabors.ImageSharp.Web" Version="2.0.2" />
  </ItemGroup>
```

Then it will compile and remove friction from installing into other projects while also omitting the undesirable modules folder.

**Comment by vnbaaij** [comment]
```
<ItemGroup>
    <None Remove="$(UserProfile)\.nuget\packages\**\*.zip" />
    <None Remove="$(UserProfile)\.nuget\packages\**\*.config" />
  </ItemGroup>
```

Would would you add this? Can imagine it giving errors in automated CI/CD workflows and also, what is in there what should not be added?

**Comment by vnbaaij** [comment]
I've uploaded version 2.1.1 which has the changes mentioned above (with exception of the $userprofile things)
