### ISSUE TITLE
All resized images get today as last modified, making caching useless

### ISSUE THREAD

**Issue by debski** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#16]
**Describe the bug**
When looking in Azure Blob Storage on the metadata of the resized images, the ones I have looked at all have today (`DateTime.Today`) as "SM" (source last modified) value. As caching looks at this value to determine if to used the cached/stored resized image or not, this can't be good. This value seems to come from `EPiServer.Azure.Blobs.Internal.AzureBlobFileInfo.LastModified`,  or possibly `EPiServer.Web.Routing.Matching.Blobs.BlobFileInfoWrapper`, which both fallback to today.

**To Reproduce**
1. Use the DXP version of image resizing with your recommended settings
2. Browse to a rescaled image
3. Look at the metadata of the generated rescaled image in Azure Blob Storage.
4. The "SM" value is incorrect

**Expected behavior**
"SM" should have the image's correct last modified data.

**Screenshots**
![image](https://user-images.githubusercontent.com/6360624/199184743-4db63b00-c55c-4367-9402-7e113926a143.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
`Baaijte.Optimizely.ImageSharp.Web.Resolvers.BlobImageResolver` seems to be where incorrect values are resolved.

**Comment by debski** [comment]
Suggested change: Update `BlobImageProvider` to send full resolved media content to `BlobImageResolver`. Then last modified date could be obtained directly from content, instead of going through hoops.

**Comment by vnbaaij** [comment]
Sorry, but I'm not actively working with Optimizely/Episerver anymore. Can you supply some code that would achieve this?

**Comment by debski** [comment]
I made a quick PR - #17 - with a suggested change. Haven't come to properly testing this change, as it requires running in DXP to test end-to-end. But at least you can see a plausible solution.

**Comment by vnbaaij** [comment]
Closed with #17. I don't have a DXP environment to test with so hopefully someone can test it for us...

Building and uploading new package now
