### ISSUE TITLE
Error when the application starts

### ISSUE THREAD

**Issue by fquintanilla** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#19]
Hi, I am using Optimizely 12.15.1 and after adding `services.AddBaaijteOptimizelyImageSharp();` in the Startup file I get this error:

`The provider root path cannot be determined, make sure it's explicitly configured or the webroot is set.`

Am I missing configuring something else? Thank!

**Comment by ErikHen** [comment]
In a newly created solution you might not have the wwwroot folder. Add that folder to fix this issue.
