### ISSUE TITLE
Bump SixLabors.ImageSharp To Version 2.1.4

### ISSUE THREAD

**Issue by ashleyjlive** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#20]
Hey,
Just wondering if the version of ImageSharp could be bumped to 2.1.4 as it fixes a fairly large bug relating to webp conversions.
Cheers.

**Comment by vnbaaij** [comment]
Hi, I just pushed version 2.1.3 of my package (which targets 2.1.4 of ImageSharp 🤔) to the NuGet feed. Should be available shortly.

**Comment by ashleyjlive** [comment]
Great, thank you! 😁
