### ISSUE TITLE
Not producing thumbnails with Image Sharp 3.1.4

### ISSUE THREAD

**Issue by veckley** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#27]
**Describe the bug**
Image Sharp 3.1.3 is reporting a vulnerability, so I updated to version 3.1.4.

Now the thumbnails within Optimizely 12 fail to generate   (currently using Framework 12.21.5)

**To Reproduce**
Update Image Sharp 3.1.4 as 3.1.3 is vulnerable

Run Optimizely and upload an image.  Thumbnail fails to generate.

**Comment by vnbaaij** [comment]
V3.0.1 has been uploade.

Package now uses:
- SixLabors.ImageSharp 3.1.4
- SixLabors.ImageSharp.Web 3.1.2
- SixLabors.ImageSharp.Web.Providers.Azure 3.1.2

I do not have any option to test this anymore. Let me know if problem is solved/not solved

**Comment by veckley** [comment]
Thank you.   I was able to grab this and test it out.   Looks like the thumbnails are still not generating.  This is probably a discrepancy with Image Sharp and Optimizely 12.    I'll play around with the different versions and see if I can get something to work.  Thank you again for your time
