### ISSUE TITLE
Query: Are there any image dimension limits in this library or it supports all kinds of images?

### ISSUE THREAD

**Issue by priyanka107** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#29]
Hi,
This is not an issue but a small query that I have. Are there any image dimension limits for this library or it supports all kinds of images?
The reason I ask - we have a few images which are of dimensions (1920 x 433 px) and they are getting cropped when resizing. Less rectangular images (800 x 500 px) are diplaying normally.

**Comment by vnbaaij** [comment]
Hi,

There are no restrictions. Itis probably just a matter of using the right configuration. Better to ask for help on World as I do not work for or with Optimizely anymore.
