### ISSUE TITLE
SixLabors.ImageSharp.Web not found at runtime

### ISSUE THREAD

**Issue by Dandroid5000** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#5]
Hi,

When I install this package via Nuget it installs the dependencies on SixLabors.ImageSharp and SixLabors.ImageSharp.Web (version 1.0.3).

See below from your nuspec file:

![image](https://user-images.githubusercontent.com/96799065/149607500-129323bb-2ac9-4765-8739-7dbaa7ab867c.png)

.. but then at runtime, I'm getting an error:

![image](https://user-images.githubusercontent.com/96799065/149607526-46957ec4-875f-4105-a1ad-4fa6970882ba.png)

I.e., it's looking for version 1.0.0.0, not the version installed by the package manager (1.0.3).

Note, if I manually update your nuspec file to look for 1.0.0 it works... but I'm not sure this is the right fix.

Let me know if I've missed something.

Thanks in advance for you help

Cheers

Dan

**Comment by Dandroid5000** [comment]
Actually, this seems to be an issue with 1.0.3 of SixLabors.ImargeSharp.Web. The dll version installed in that package is 0.0.0.0. Can you update your package to look for 1.0.5? That seems to work

**Comment by vnbaaij** [comment]
I've uploaded a new version of the package (1.0.6) to the feed that uses ImageSharp.Web 1.0.5. Let me know if it works ok now. Thanks.

**Comment by Dandroid5000** [comment]
Thanks @vnbaaij ! Yes, this is fixed now. Thanks so much.
