### ISSUE TITLE
Connection strings/container names from config

### ISSUE THREAD

**Issue by Nhawdge** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#6]
This isn't a bug per se, but just an issue with DXP configuration: 

In the Readme there's a setup for DXP sites. I've been having trouble locating any documentation about what those keys are from configuration. They used to be `EPiServer:Cms:AzureBlobProvider:ConnectionString` and `EPiServer:Cms:AzureBlobProvider:ContainerName`.  Any chance you've run into this and know what the keys are? Thanks!

**Comment by jsalwen** [comment]
We are having the same issue

**Comment by vnbaaij** [comment]
Sorry, but I don't have access to a DXP environment to check. Think you can better ask this on World.

**Comment by Nhawdge** [comment]
Thanks for the reply. For future readers I've posted the question on World.

https://world.optimizely.com/forum/developer-forum/CMS/Thread-Container/2022/2/connection-information-for-azure-blob-storage-for-imagesharp/
