### ISSUE TITLE
Resize image doesn't seem working within CMS in edit/preview mode

### ISSUE THREAD

**Issue by javafun** [vnbaaij/Baaijte.Optimizely.ImageSharp.Web#9]
Hi @vnbaaij 

I noticed images are not resized properly when in edit/preview mode. I follow the readme instruction and add required code to both ConfigureService and Configure method. Is there anything else I need to configure? Thanks

![image](https://user-images.githubusercontent.com/332991/160727265-8b32517e-4df5-4bbe-a2b8-7e5758cd92e6.png)

```html
<img src="@Url.ContentUrl(Model.MyImage)?width=150" alt="" />
```

**Comment by vnbaaij** [comment]
Sorry, I don't have a CMS installation at hand that I can test with/in. Maybe ask on World?

**Comment by javafun** [comment]
Hi @vnbaaij 

I can provide a CMS example if needed. The middleware doesn't seem taking the CMS internal url into account (see attached below). Do you have solution for this? Thanks

![image](https://user-images.githubusercontent.com/332991/191749960-ac5191c2-c3a5-452c-90ae-f530775b6f12.png)

**Comment by vnbaaij** [comment]
Hi,

I'm not working with (and for) Optimizely anymore and don't have the time to work on this.
Happy to take a PR if you have a solution. Otherwise maybe @erikhen can take a look?
